[package]
name = "shopify-challenge"
version = "0.1.0"
authors = ["Jiayi Zhao <jeff.no.zhao@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
lazy_static = "1.2.0"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0"
