[global.limits]
forms = 32768

[development]
address = "localhost"
port = 8000
workers = 1
keep_alive = 5
log = "normal"

[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log = "normal"

[production]
address = "138.51.0.143"
port = 8000
workers = 12
keep_alive = 5
log = "critical"
